# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blue Buddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blue Buddy
  pod 'MICountryPicker', :git => 'https://github.com/mustafaibrahim989/MICountryPicker.git', :branch => 'master'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'MarqueeLabel/Swift'
  pod 'IQKeyboardManager'
  pod 'NVActivityIndicatorView'
  pod 'FloatRatingView', '~> 2.0.0'
  pod 'Kingfisher', '~> 3.0'
  pod 'OpalImagePicker', '~> 1.4.0'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'JSQMessagesViewController'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'SKPhotoBrowser', '~> 4.0.0'

end
	
